name: generate_orders
sql_file: insert_orders.sql
total_rows: 30000000
batch_size: 50000
description: Generate 30M orders in batches of 50k
parameters:
  min_amount: 10.00
  max_amount: 1000.00
  min_tax_percent: 5
  max_tax_percent: 15
  min_due_days: 7
  max_due_days: 60
